services:
  # Servicio Backend (Spring Boot)
  - type: web
    name: backend-service
    env: docker
    dockerfilePath: ./Dockerfile.backend
    branch: staging
    plan: free
    autoDeploy: false

  # Servicio Frontend (Angular)
  - type: web
    name: frontend-service
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    branch: staging
    plan: free
    autoDeploy: false
